export const data = {
  name: "Gayatri Siddha",
  role: "Full-Stack Developer",
  email: "gayatrisiddha04@gmail.com",
  phone: "+91-7720845600",
  location: "Pune, India",
  linkedin: "https://linkedin.com/in/gayatri-siddha",
  github: "https://github.com/gayatrisiddha",
  resume: "/Gayatri-Full-StackDeveloper.pdf",

  summary:
    "I build fast, interactive web experiences — from educational games deployed in the wild, to AI-powered platforms, to cross-platform apps. Strong in React, Java, and everything in between.",

  stats: [
    { number: "7+", label: "Months intern @ Jyotirgamay" },
    { number: "4", label: "Projects shipped" },
    { number: "10+", label: "Technologies" },
    { number: "∞", label: "Bugs squashed 🐛" },
  ],

  experience: [
    {
      role: "Frontend Developer Intern",
      company: "Jyotirgamay Solutions",
      period: "December 2024 – June 2025",
      color: "--lime",
      points: [
        "Built Habitat Matcher, an interactive educational game with ReactJS, PhaserJS, and Vite — live on kiosk screens at Empress Garden.",
        "Designed an interactive U.S. sales tax map for JyoTax using React and react-simple-maps with tooltips and animations.",
        "Worked across game dev, static & dynamic websites, and data visualization projects.",
      ],
    },
    {
      role: "Java Full-Stack Trainee",
      company: "Linkcode Technologies Pvt. Ltd.",
      period: "August 2022 – June 2023",
      color: "--sky",
      points: [
        "Completed full-stack Java training — OOP, exception handling, multithreading, and collections.",
        "Built web applications with JSP and Servlets; gained frontend experience with ReactJS.",
        "Hands-on debugging and development using Eclipse and Maven.",
      ],
    },
  ],

  skills: [
    { category: "Frontend",    color: "--pink",  tags: ["ReactJS", "Next.js", "Angular", "JavaScript", "TypeScript", "HTML", "CSS", "PhaserJS", "Bootstrap", "Tailwind CSS"] },
    { category: "Backend",     color: "--sky",   tags: ["Java", "Spring Boot", "Hibernate", "RESTful APIs", "Microservices", "Servlets", "MVC"] },
    { category: "Mobile",      color: "--lime",  tags: ["React Native"] },
    { category: "Databases",   color: "--amber", tags: ["MySQL", "PostgreSQL", "SQL Server"] },
    { category: "Tools",       color: "--mint",  tags: ["Git", "GitHub", "VS Code", "Postman", "JIRA", "Maven", "Swagger", "Eclipse"] },
    { category: "Methods",     color: "--coral", tags: ["Agile", "Scrum", "SDLC", "Problem Solving"] },
  ],

  projects: [
    {
      title: "Habitat Matcher",
      type: "Educational Game • Live at Empress Garden",
      emoji: "🦁",
      bg: "linear-gradient(135deg,#0d2200,#1a4400)",
      accent: "--lime",
      desc: "An interactive educational game helping visitors learn about animals and their natural habitats. Built for RRBCEA and deployed on kiosk screens at Empress Garden, Pune.",
      stack: ["ReactJS", "PhaserJS", "JavaScript", "Vite"],
      live: "http://games.rrbcea.org/",
      github: null,
      status: "Live",
    },
    {
      title: "JyoTax",
      type: "AI Tax Platform",
      emoji: "💸",
      bg: "linear-gradient(135deg,#001a2e,#003352)",
      accent: "--sky",
      desc: "AI-powered tax management platform. Built interactive U.S. sales tax maps, responsive dashboards, dynamic charts, and data visualizations for a seamless filing experience.",
      stack: ["ReactJS", "Next.js", "Tailwind CSS", "react-simple-maps"],
      live: "https://jyotax.ai/",
      github: null,
      status: "Live",
    },
    {
      title: "Hampi Travel",
      type: "Travel App • Ongoing",
      emoji: "🏛️",
      bg: "linear-gradient(135deg,#2e1a00,#523300)",
      accent: "--amber",
      desc: "A travel companion web app for Hampi — featuring heritage site guides, interactive maps, itinerary planner, and local tips for one of India's most stunning destinations.",
      stack: ["ReactJS", "CSS"],
      live: null,
      github: null,
      status: "In Progress",
    },
    {
      title: "My Society App",
      type: "Mobile App • Ongoing",
      emoji: "🏘️",
      bg: "linear-gradient(135deg,#1a002e,#33005e)",
      accent: "--pink",
      desc: "A React Native app for housing society management — visitor logs, maintenance requests, announcements, and resident directory, all in one place.",
      stack: ["React Native"],
      live: null,
      github: null,
      status: "In Progress",
    },
    {
      title: "Customer Account Management",
      type: "Java Full-Stack",
      emoji: "🗄️",
      bg: "linear-gradient(135deg,#001a1a,#003333)",
      accent: "--mint",
      desc: "A secure web app for managing customer profiles and financial data. Follows DAO pattern + MVC architecture with password hashing and session management.",
      stack: ["Java", "JSP", "Servlets", "JDBC", "MySQL"],
      live: null,
      github: null,
      status: "Completed",
    },
  ],

  education: {
    degree: "B.E.",
    university: "Savitribai Phule Pune University",
    cgpa: "7.4",
    location: "Pune",
  },
}
